# Implante um Deployment chamado "my-deployment" com três réplicas de uma aplicação baseada na imagem "httpd". Atualize a imagem do Deployment para uma versão mais recente.

# por comando
# criar o deployment
# kubectl create deployment my-deployment --image=httpd --replicas=1

# atualizar a imagem
# kubectl set image deployment/my-deployment httpd=httpd:latest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        # image: httpd:latest -> versão atualizada
        ports:
        - containerPort: 80
