# Configure um PersistentVolume de 1Gi de armazenamento local e vincule-o a um PersistentVolumeClaim. Monte o volume em um pod e salve arquivos para verificar a persistência.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pod-local-storage
spec:
  storageClassName: storagetestpod
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/test-pod/"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pod-pvc
spec:
  storageClassName: storagetestpod
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: volume-in-test-pod
          mountPath: /usr/share/nginx/html
  volumes:
    - name: volume-in-test-pod
      persistentVolumeClaim:
        claimName: test-pod-pvc
