
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    metadata:
      name: batch-job
    spec:
      containers:
      - name: batch-container
        image: busybox # imagem pequena para testes
        command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never
