# Implante um Job chamado "batch-job" que execute um comando simples e termine. Verifique os logs do Job para confirmar sua execução.

# verififcar os logs: kubectl logs batch-job-2zvm
# deve retornar: Hello, Kubernetes!
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    metadata:
      name: batch-job
    spec:
      containers:
      - name: batch-container
        image: busybox # imagem pequena para testes
        command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never
