
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQxMjM=  # "password123" codificado em base64
  API_KEY: YXBpX2tleV9leGFtcGxl  # "api_key_example" codificado em base64
---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod-secret
spec:
  containers:
    - name: app-container
      image: nginx
      envFrom:
        - secretRef:
            name: app-secret