# Crie um pod chamado "restart-pod" com a política de reinício configurada como "OnFailure". Provoque uma falha no pod e observe seu comportamento.

# verificar a falha: kubectl get po restart-pod
# deve informar que está falhando!
apiVersion: v1
kind: Pod
metadata:
  name: restart-pod
spec:
  containers:
  - name: failing-container
    image: busybox
    command: ["sh", "-c", "exit 1"]
  restartPolicy: OnFailure