
apiVersion: v1
kind: Pod
metadata:
  name: restart-pod
spec:
  containers:
  - name: failing-container
    image: busybox
    command: ["sh", "-c", "exit 1"]
  restartPolicy: OnFailure

docker run -d --name my-container busybox sh -c "i=1; while true; do echo \"Hello \$i\"; i=\$((i+1)); sleep 1; done"
